# Generated by Django 5.0.3 on 2024-12-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('category', models.IntegerField(choices=[(1, 'Овощи'), (2, 'Фрукты'), (3, 'Зелень'), (4, 'Сухофрукты'), (5, 'Прочее')], verbose_name='Категория')),
                ('unit', models.IntegerField(choices=[(1, 'килограмм'), (2, 'коробка/ящик'), (3, 'мешок/пакет')], verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное наименование')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.product')),
            ],
        ),
    ]
